Last fix script deploy

diff --git a/.github/workflows/github-actions-prod.yml b/.github/workflows/github-actions-prod.yml
--- a/.github/workflows/github-actions-prod.yml
+++ b/.github/workflows/github-actions-prod.yml
@@ -36,7 +36,13 @@ jobs:
         run: sleep 30s
 
       - name: Run a curl test
-        run: curl http://localhost:8080/api/cities?query
+        run: |
+          response_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/api/cities?query)
+          if [ $response_code -ne 200 ]; then
+            echo "Curl test failed with response code $response_code"
+            exit 1
+          fi
+          echo "Curl test passed with response code $response_code"
 
       - name: Run tests (phpUnit)
         run: docker exec app-container ./html/vendor/bin/phpunit --verbose ./html/App/Test/ApiTest --stderr
